name: Publish to npm

on:
  push:
    branches:
      - develop

jobs:
  publsih:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm build:lib
      - run: cd projects/ds-ng/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
